# Generated by Django 2.2.1 on 2019-06-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchdetails', '0002_auto_20190617_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='non_strike',
            new_name='non_striker',
        ),
    ]
