# Generated by Django 2.2.1 on 2019-06-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchdetails', '0003_auto_20190617_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='wideruns',
            new_name='wide_runs',
        ),
    ]
