# Generated by Django 2.2.1 on 2019-06-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchdetails', '0004_auto_20190617_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='leg_bye_runs',
            new_name='legbye_runs',
        ),
    ]
